package mx.ine.sscc.modelo.entidad;

// Generated 7/10/2015 03:44:59 PM by Hibernate Tools 4.0.0

/**
 * RespuestasPK generated by hbm2java
 */
public class RespuestasPK implements java.io.Serializable {

    /**
     * TODO [Agregar documentación del atributo]
     */

    private static final long serialVersionUID = 1L;
    private String folioSi;
    private Integer cuestionarioId;
    private Integer preguntaId;
    private String candidatoId;

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     */
    public RespuestasPK() {
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @param folioSi
     * @param cuestionarioId
     * @param preguntaId
     * @param candidatoId
     */
    public RespuestasPK(String folioSi, Integer cuestionarioId, Integer preguntaId,
        String candidatoId) {
        this.folioSi = folioSi;
        this.cuestionarioId = cuestionarioId;
        this.preguntaId = preguntaId;
        this.candidatoId = candidatoId;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @return String
     */
    public String getFolioSi() {
        return this.folioSi;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @param folioSi
     */
    public void setFolioSi(String folioSi) {
        this.folioSi = folioSi;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @return Integer
     */
    public Integer getCuestionarioId() {
        return this.cuestionarioId;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @param cuestionarioId
     */
    public void setCuestionarioId(Integer cuestionarioId) {
        this.cuestionarioId = cuestionarioId;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @return Integer
     */
    public Integer getPreguntaId() {
        return this.preguntaId;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @param preguntaId
     */
    public void setPreguntaId(Integer preguntaId) {
        this.preguntaId = preguntaId;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @return String
     */
    public String getCandidatoId() {
        return this.candidatoId;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @param candidatoId
     */
    public void setCandidatoId(String candidatoId) {
        this.candidatoId = candidatoId;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof RespuestasPK)) {
            return false;
        }
        RespuestasPK castOther = (RespuestasPK) other;

        return ((this.getFolioSi() == castOther.getFolioSi()) || (this.getFolioSi() != null
            && castOther.getFolioSi() != null && this.getFolioSi().equals(
            castOther.getFolioSi())))
            && (this.getCuestionarioId() == castOther.getCuestionarioId())
            && (this.getPreguntaId() == castOther.getPreguntaId())
            && ((this.getCandidatoId() == castOther.getCandidatoId()) || (this.getCandidatoId() != null
                && castOther.getCandidatoId() != null && this.getCandidatoId().equals(
                castOther.getCandidatoId())));
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getFolioSi() == null ? 0 : this.getFolioSi().hashCode());
        result = 37 * result + this.getCuestionarioId();
        result = 37 * result + (this.getPreguntaId());
        result =
            37 * result + (getCandidatoId() == null ? 0 : this.getCandidatoId().hashCode());
        return result;
    }

}
