package mx.ine.sscc.modelo.entidad;

// Generated 7/10/2015 03:44:59 PM by Hibernate Tools 4.0.0

/**
 * SituacionRegistralPK generated by hbm2java
 */
public class SituacionRegistralPK implements java.io.Serializable {

    /**
     * TODO [Agregar documentación del atributo]
     */

    private static final long serialVersionUID = 1L;
    private String folioSi;
    private Integer cuestionarioId;

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     */
    public SituacionRegistralPK() {
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @param folioSi
     * @param cuestionarioId
     */
    public SituacionRegistralPK(String folioSi, Integer cuestionarioId) {
        this.folioSi = folioSi;
        this.cuestionarioId = cuestionarioId;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @return String
     */
    public String getFolioSi() {
        return this.folioSi;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @param folioSi
     */
    public void setFolioSi(String folioSi) {
        this.folioSi = folioSi;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @return Integer
     */
    public Integer getCuestionarioId() {
        return this.cuestionarioId;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Luis Gerardo Dávila López (gerardo.d@hotmail.com)
     * @param cuestionarioId
     */
    public void setCuestionarioId(Integer cuestionarioId) {
        this.cuestionarioId = cuestionarioId;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof SituacionRegistralPK)) {
            return false;
        }
        SituacionRegistralPK castOther = (SituacionRegistralPK) other;

        return ((this.getFolioSi() == castOther.getFolioSi()) || (this.getFolioSi() != null
            && castOther.getFolioSi() != null && this.getFolioSi().equals(
            castOther.getFolioSi())))
            && (this.getCuestionarioId() == castOther.getCuestionarioId());
    }

    @Override
    public int hashCode() {
        int result = 17;

        result = 37 * result + (getFolioSi() == null ? 0 : this.getFolioSi().hashCode());
        result = 37 * result + this.getCuestionarioId();
        return result;
    }

}
