package mx.ine.sscc.modelo.entidad;
// Generated 28/10/2015 10:33:18 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Tmpcredencialunica generated by hbm2java
 */
public class TmpCredencialUnica implements java.io.Serializable {

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("credencialId=");
        builder.append(credencialId);
        builder.append(", ciudadanoId=");
        builder.append(ciudadanoId);
        builder.append(", claveunicaciudadanoId=");
        builder.append(claveunicaciudadanoId);
        builder.append(", estatuscredencialId=");
        builder.append(estatuscredencialId);
        builder.append(", claveElector=");
        builder.append(claveElector);
        builder.append(", numEmisionCredencial=");
        builder.append(numEmisionCredencial);
        builder.append(", ocr=");
        builder.append(ocr);
        builder.append(", cic=");
        builder.append(cic);
        builder.append(", curp=");
        builder.append(curp);
        builder.append(", fechaInscripcionPadron=");
        builder.append(fechaInscripcionPadron);
        builder.append(", nombre=");
        builder.append(nombre);
        builder.append(", apellidoPaterno=");
        builder.append(apellidoPaterno);
        builder.append(", apellidoMaterno=");
        builder.append(apellidoMaterno);
        builder.append(", huellasId=");
        builder.append(huellasId);
        builder.append(", estatusciudadanoId=");
        builder.append(estatusciudadanoId);
        builder.append(", tipobajapadronId=");
        builder.append(tipobajapadronId);
        builder.append(", residenteExtranjero=");
        builder.append(residenteExtranjero);
        builder.append(", fechaCreacion=");
        builder.append(fechaCreacion);
        builder.append(", fechaUltimoTramite=");
        builder.append(fechaUltimoTramite);
        builder.append(", vigenciaCredencial=");
        builder.append(vigenciaCredencial);
        builder.append(", entidadId=");
        builder.append(entidadId);
        builder.append(", seccion=");
        builder.append(seccion);
        builder.append(", tiporeincorporacionpadronId=");
        builder.append(tiporeincorporacionpadronId);
        builder.append(", reporteroboextravioId=");
        builder.append(reporteroboextravioId);
        builder.append(", estatusroboextravio=");
        builder.append(estatusroboextravio);
        builder.append(", causaroboextravio=");
        builder.append(causaroboextravio);
        builder.append(", fechaInsercion=");
        builder.append(fechaInsercion);
        return builder.toString();
    }

    /**
     * TODO [Agregar documentación del atributo]
     */

    private static final long serialVersionUID = 1L;
    private long credencialId;
    private long ciudadanoId;
    private Long claveunicaciudadanoId;
    private Byte estatuscredencialId;
    private String claveElector;
    private byte numEmisionCredencial;
    private String ocr;
    private String cic;
    private String curp;
    private Date fechaInscripcionPadron;
    private String nombre;
    private String apellidoPaterno;
    private String apellidoMaterno;
    private Long huellasId;
    private byte estatusciudadanoId;
    private Byte tipobajapadronId;
    private Boolean residenteExtranjero;
    private Date fechaCreacion;
    private Date fechaUltimoTramite;
    private Date vigenciaCredencial;
    private byte entidadId;
    private String seccion;
    private Byte tiporeincorporacionpadronId;
    private Long reporteroboextravioId;
    private Byte estatusroboextravio;
    private Byte causaroboextravio;
    private Date fechaInsercion;

    /**
     * TODO [Agregar documentacion al método]
     * @author Orlando Ramos Galván (orlandoa.ramos@outlook.com)
     */
    public TmpCredencialUnica() {
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Orlando Ramos Galván (orlandoa.ramos@outlook.com)
     * @param credencialId
     * @param ciudadanoId
     * @param claveElector
     * @param numEmisionCredencial
     * @param fechaInscripcionPadron
     * @param estatusciudadanoId
     * @param entidadId
     */
    public TmpCredencialUnica(long credencialId, long ciudadanoId, String claveElector,
        byte numEmisionCredencial, Date fechaInscripcionPadron, byte estatusciudadanoId,
        byte entidadId) {
        this.credencialId = credencialId;
        this.ciudadanoId = ciudadanoId;
        this.claveElector = claveElector;
        this.numEmisionCredencial = numEmisionCredencial;
        this.fechaInscripcionPadron = fechaInscripcionPadron;
        this.estatusciudadanoId = estatusciudadanoId;
        this.entidadId = entidadId;
    }

    /**
     * TODO [Agregar documentacion al método]
     * @author Orlando Ramos Galván (orlandoa.ramos@outlook.com)
     * @param credencialId
     * @param ciudadanoId
     * @param claveunicaciudadanoId
     * @param estatuscredencialId
     * @param claveElector
     * @param numEmisionCredencial
     * @param ocr
     * @param cic
     * @param curp
     * @param fechaInscripcionPadron
     * @param nombre
     * @param apellidoPaterno
     * @param apellidoMaterno
     * @param huellasId
     * @param estatusciudadanoId
     * @param tipobajapadronId
     * @param residenteExtranjero
     * @param fechaCreacion
     * @param fechaUltimoTramite
     * @param vigenciaCredencial
     * @param entidadId
     * @param seccion
     * @param tiporeincorporacionpadronId
     * @param reporteroboextravioId
     * @param estatusroboextravio
     * @param causaroboextravio
     * @param fechaInsercion
     */
    public TmpCredencialUnica(long credencialId, long ciudadanoId, Long claveunicaciudadanoId,
        Byte estatuscredencialId, String claveElector, byte numEmisionCredencial, String ocr,
        String cic, String curp, Date fechaInscripcionPadron, String nombre,
        String apellidoPaterno, String apellidoMaterno, Long huellasId,
        byte estatusciudadanoId, Byte tipobajapadronId, Boolean residenteExtranjero,
        Date fechaCreacion, Date fechaUltimoTramite, Date vigenciaCredencial, byte entidadId,
        String seccion, Byte tiporeincorporacionpadronId, Long reporteroboextravioId,
        Byte estatusroboextravio, Byte causaroboextravio, Date fechaInsercion) {
        this.credencialId = credencialId;
        this.ciudadanoId = ciudadanoId;
        this.claveunicaciudadanoId = claveunicaciudadanoId;
        this.estatuscredencialId = estatuscredencialId;
        this.claveElector = claveElector;
        this.numEmisionCredencial = numEmisionCredencial;
        this.ocr = ocr;
        this.cic = cic;
        this.curp = curp;
        this.fechaInscripcionPadron = fechaInscripcionPadron;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
        this.huellasId = huellasId;
        this.estatusciudadanoId = estatusciudadanoId;
        this.tipobajapadronId = tipobajapadronId;
        this.residenteExtranjero = residenteExtranjero;
        this.fechaCreacion = fechaCreacion;
        this.fechaUltimoTramite = fechaUltimoTramite;
        this.vigenciaCredencial = vigenciaCredencial;
        this.entidadId = entidadId;
        this.seccion = seccion;
        this.tiporeincorporacionpadronId = tiporeincorporacionpadronId;
        this.reporteroboextravioId = reporteroboextravioId;
        this.estatusroboextravio = estatusroboextravio;
        this.causaroboextravio = causaroboextravio;
        this.fechaInsercion = fechaInsercion;
    }

    public long getCredencialId() {
        return this.credencialId;
    }

    /**
     * @param credencialId
     */
    public void setCredencialId(long credencialId) {
        this.credencialId = credencialId;
    }

    /**
     * @return
     */
    public long getCiudadanoId() {
        return this.ciudadanoId;
    }

    /**
     * @param ciudadanoId
     */
    public void setCiudadanoId(long ciudadanoId) {
        this.ciudadanoId = ciudadanoId;
    }

    /**
     * @return
     */
    public Long getClaveunicaciudadanoId() {
        return this.claveunicaciudadanoId;
    }

    /**
     * @param claveunicaciudadanoId
     */
    public void setClaveunicaciudadanoId(Long claveunicaciudadanoId) {
        this.claveunicaciudadanoId = claveunicaciudadanoId;
    }

    /**
     * @return
     */
    public Byte getEstatuscredencialId() {
        return this.estatuscredencialId;
    }

    /**
     * @param estatuscredencialId
     */
    public void setEstatuscredencialId(Byte estatuscredencialId) {
        this.estatuscredencialId = estatuscredencialId;
    }

    /**
     * @return
     */
    public String getClaveElector() {
        return this.claveElector;
    }

    /**
     * @param claveElector
     */
    public void setClaveElector(String claveElector) {
        this.claveElector = claveElector;
    }

    /**
     * @return
     */
    public byte getNumEmisionCredencial() {
        return this.numEmisionCredencial;
    }

    /**
     * @param numEmisionCredencial
     */
    public void setNumEmisionCredencial(byte numEmisionCredencial) {
        this.numEmisionCredencial = numEmisionCredencial;
    }

    /**
     * @return
     */
    public String getOcr() {
        return this.ocr;
    }

    /**
     * @param ocr
     */
    public void setOcr(String ocr) {
        this.ocr = ocr;
    }

    /**
     * @return
     */
    public String getCic() {
        return this.cic;
    }

    /**
     * @param cic
     */
    public void setCic(String cic) {
        this.cic = cic;
    }

    /**
     * @return
     */
    public String getCurp() {
        return this.curp;
    }

    /**
     * @param curp
     */
    public void setCurp(String curp) {
        this.curp = curp;
    }

    /**
     * @return
     */
    public Date getFechaInscripcionPadron() {
        return this.fechaInscripcionPadron;
    }

    /**
     * @param fechaInscripcionPadron
     */
    public void setFechaInscripcionPadron(Date fechaInscripcionPadron) {
        this.fechaInscripcionPadron = fechaInscripcionPadron;
    }

    /**
     * @return
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     * @param nombre
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * @return
     */
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }

    /**
     * @param apellidoPaterno
     */
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    /**
     * @return
     */
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }

    /**
     * @param apellidoMaterno
     */
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    /**
     * @return
     */
    public Long getHuellasId() {
        return this.huellasId;
    }

    /**
     * @param huellasId
     */
    public void setHuellasId(Long huellasId) {
        this.huellasId = huellasId;
    }

    /**
     * @return
     */
    public byte getEstatusciudadanoId() {
        return this.estatusciudadanoId;
    }

    /**
     * @param estatusciudadanoId
     */
    public void setEstatusciudadanoId(byte estatusciudadanoId) {
        this.estatusciudadanoId = estatusciudadanoId;
    }

    /**
     * @return
     */
    public Byte getTipobajapadronId() {
        return this.tipobajapadronId;
    }

    /**
     * @param tipobajapadronId
     */
    public void setTipobajapadronId(Byte tipobajapadronId) {
        this.tipobajapadronId = tipobajapadronId;
    }

    /**
     * @return
     */
    public Boolean getResidenteExtranjero() {
        return this.residenteExtranjero;
    }

    /**
     * @param residenteExtranjero
     */
    public void setResidenteExtranjero(Boolean residenteExtranjero) {
        this.residenteExtranjero = residenteExtranjero;
    }

    /**
     * @return
     */
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    /**
     * @param fechaCreacion
     */
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    /**
     * @return
     */
    public Date getFechaUltimoTramite() {
        return this.fechaUltimoTramite;
    }

    /**
     * @param fechaUltimoTramite
     */
    public void setFechaUltimoTramite(Date fechaUltimoTramite) {
        this.fechaUltimoTramite = fechaUltimoTramite;
    }

    /**
     * @return
     */
    public Date getVigenciaCredencial() {
        return this.vigenciaCredencial;
    }

    /**
     * @param vigenciaCredencial
     */
    public void setVigenciaCredencial(Date vigenciaCredencial) {
        this.vigenciaCredencial = vigenciaCredencial;
    }

    /**
     * @return
     */
    public byte getEntidadId() {
        return this.entidadId;
    }

    /**
     * @param entidadId
     */
    public void setEntidadId(byte entidadId) {
        this.entidadId = entidadId;
    }

    /**
     * @return
     */
    public String getSeccion() {
        return this.seccion;
    }

    /**
     * @param seccion
     */
    public void setSeccion(String seccion) {
        this.seccion = seccion;
    }

    /**
     * @return
     */
    public Byte getTiporeincorporacionpadronId() {
        return this.tiporeincorporacionpadronId;
    }

    /**
     * @param tiporeincorporacionpadronId
     */
    public void setTiporeincorporacionpadronId(Byte tiporeincorporacionpadronId) {
        this.tiporeincorporacionpadronId = tiporeincorporacionpadronId;
    }

    /**
     * @return
     */
    public Long getReporteroboextravioId() {
        return this.reporteroboextravioId;
    }

    /**
     * @param reporteroboextravioId
     */
    public void setReporteroboextravioId(Long reporteroboextravioId) {
        this.reporteroboextravioId = reporteroboextravioId;
    }

    /**
     * @return
     */
    public Byte getEstatusroboextravio() {
        return this.estatusroboextravio;
    }

    /**
     * @param estatusroboextravio
     */
    public void setEstatusroboextravio(Byte estatusroboextravio) {
        this.estatusroboextravio = estatusroboextravio;
    }

    /**
     * @return
     */
    public Byte getCausaroboextravio() {
        return this.causaroboextravio;
    }

    /**
     * @param causaroboextravio
     */
    public void setCausaroboextravio(Byte causaroboextravio) {
        this.causaroboextravio = causaroboextravio;
    }

    /**
     * @return
     */
    public Date getFechaInsercion() {
        return this.fechaInsercion;
    }

    /**
     * @param fechaInsercion
     */
    public void setFechaInsercion(Date fechaInsercion) {
        this.fechaInsercion = fechaInsercion;
    }

}
