//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.12.16 at 12:34:33 PM CST
//

package mx.ine.sscc.servicios.unicom.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="estatusCredencial" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="fechaEstatus" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="folioFuar" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="moduloIFEID" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "estatusCredencial", "fechaEstatus", "folioFuar",
    "moduloIFEID" })
@XmlRootElement(name = "detalleEstatusCredencial")
public class DetalleEstatusCredencial {

    protected byte estatusCredencial;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar fechaEstatus;
    protected String folioFuar;
    protected String moduloIFEID;

    /**
     * Gets the value of the estatusCredencial property.
     *
     */
    public byte getEstatusCredencial() {
        return estatusCredencial;
    }

    /**
     * Sets the value of the estatusCredencial property.
     * @param value
     *
     */
    public void setEstatusCredencial(byte value) {
        this.estatusCredencial = value;
    }

    /**
     * Gets the value of the fechaEstatus property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFechaEstatus() {
        return fechaEstatus;
    }

    /**
     * Sets the value of the fechaEstatus property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setFechaEstatus(XMLGregorianCalendar value) {
        this.fechaEstatus = value;
    }

    /**
     * Gets the value of the folioFuar property.
     *
     */
    public String getFolioFuar() {
        return folioFuar;
    }

    /**
     * Sets the value of the folioFuar property.
     * @param value
     *
     */
    public void setFolioFuar(String value) {
        this.folioFuar = value;
    }

    /**
     * Gets the value of the moduloIFEID property.
     * @return moduloIFEID
     *
     */
    public String getModuloIFEID() {
        return moduloIFEID;
    }

    /**
     * Sets the value of the moduloIFEID property.
     * @param value
     *
     */
    public void setModuloIFEID(String value) {
        this.moduloIFEID = value;
    }

    /* La documentación de este método se encuentra en la clase o interface que
     * lo declara  (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("estatusCredencial=")
            .append(estatusCredencial)
            .append(", fechaEstatus=")
            .append(fechaEstatus)
            .append(", folioFuar=")
            .append(folioFuar)
            .append(", moduloIFEID=")
            .append(moduloIFEID);
        return builder.toString();
    }

}
